### ISSUE TITLE
About  tune 

### ISSUE THREAD

**Issue by frg01** [postgresml/postgresml#1256]
I checked the documentation on the official website to learn about the usage of tune.
The tune method can only tune the Hugging Face model. My local train classification or regression model does not support fine-tuning, right? So how do I tune the model I trained myself local? 
Is tuning the local model a necessary function?

example： 
--- select pg_ml.load_dataset('iris');

--- SELECT pg_ml.train(
project_name => 'preprocessed_model',
task => 'classification',
relation_name => 'iris',
target => 'Class',
preprocess => '{
"Class": {"encode": "target"}
}'
);

now i can't tune this preprocessed_model ,I was confused.

**Comment by montanalow** [comment]
Generally speaking, it would be atypical to tune a model that has been trained on the same dataset, because training should have extracted all useful information in that step. Tuning is typically only done when you have a pretrained model on some other dataset, and need to specialize it on a new dataset, while retaining some of the more general original work. Some (most?) ML algorithms will not react well or support tuning on a second dataset, so this is typically only done with LLMs. 

The typical use case, that is supported by PostgresML, is to download a pretrained LLM from HuggingFace, and fine tune it on your own data, although there is a lot of work to be done to support all the fine tuning possibilities. See also #677

**Comment by montanalow** [comment]
To answer your question more directly, I don't thing you need to tune at all. `pgml.train` with classical ML algorithms is the complete workflow. The preprocessing that is applied during training, is also applied during `pgml.predict` with that model, so you don't have to worry about processing your prediction inputs.

**Comment by frg01** [comment]
Thank you for your reply, it's great that you can answer such a basic question.
