### ISSUE TITLE
`pgml.predict` does not work with specific models that are not the deployed model

### ISSUE THREAD

**Issue by gaspardc-met** [postgresml/postgresml#1643]
The documentation of `pgml.predict` states that you can use a model id to predict with a specific model. 
![image](https://github.com/user-attachments/assets/7c1f0e89-c71f-4f42-8c78-3ca7dd190c5b)

However, this does not seem to be possible with the current code on main:
![image](https://github.com/user-attachments/assets/2e5ec94c-181b-4aba-827b-6d630537c1ed)

This despite the model ID corresponding to a model in this project: 
![image](https://github.com/user-attachments/assets/fdce1651-f049-453d-b0f4-150a60f8f33b)

Is this a planned feature or a deprecated feature ?

**Comment by montanalow** [comment]
Are you passing a `TEXT` rather than `INTEGER` as the model_id? This function is overloaded and `TEXT` is interpreted as a project.name. We have a test for this functionality in the examples that currently passes:

https://github.com/postgresml/postgresml/blob/master/pgml-extension/examples/regression.sql#L30

**Comment by montanalow** [comment]
You should be using bind parameters, per the psycopg documentation. String interpolation is fraught with bugs and security risks.

https://www.psycopg.org/psycopg3/docs/basic/params.html
