### ISSUE TITLE
Add authentication support to the dashboard

### ISSUE THREAD

**Issue by chikkujimmy** [postgresml/postgresml#168]
Since the application is open we tried to deploy in Nginx and Traefik using basic authorization. After setting up the authorization when we try to create a new project the next button doesn't work. But when the basic authorization is disabled both in Nginx and Traefik then the Next button works while creating a project. Attaching the screenshots for your reference. 
        

1.  Failed to load resource: the server responded with a status of 403 () new-project.js:83     
4.  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length') at new-project.js:83:26

![auth](https://user-images.githubusercontent.com/108451160/177310118-716bf834-2cb4-4da5-8e79-916a0ee73de4.jpg)

![error posgresml](https://user-images.githubusercontent.com/108451160/177309954-ff242e7a-6219-4ef9-9c70-611c359f8bb6.jpg)

It would be great if you could advise on how we can secure postgresml with an authentication service.

**Comment by montanalow** [comment]
My guess is this is actually related to ngninx SSL configs. The 403 is most
likely generated by CSRF protection. Can you post your nginx config as
well? There may also be some hints in this thread.

https://forum.djangoproject.com/t/csrf-validation-failure-due-to-https/3023

**Comment by chikkujimmy** [comment]
Thanks for the quick response. I have tried with and with ought SSL and still the issue persists. When I add a basic auth in nginx default.conf file with the below entries where I have generated a .htpasswd file which contains encrypted username and password. This would secure the end point and when I visit the deployed postgresml in a web browser it will ask for a username and password where I will have to enter the username and password which I have specified in the .htpasswd file. This will login in to the postgresml main page and then when I create a New project and type in the project name the green tick wont appear and if you hover over to the next button it will show a no entry sign and the button wont be clickable.

If you have any other alternatives or suggestions to secure the endpoint then please let me know and I will try it out. 

Please find below images FYR

NGINX CONF
==================================
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
=================================

![login page](https://user-images.githubusercontent.com/108451160/177498110-4dda1a32-25bf-419e-92b4-1da5c26e3ea9.jpg)

![withought sslnew](https://user-images.githubusercontent.com/108451160/177498145-b0f145f2-3f0a-4ef3-bc66-e9c06e691cab.jpg)

**Comment by levkk** [comment]
Securing the deployment of a web app is a fairly complex subject. Depending on where it runs and who needs access, security has different layers and problems.

If you're running it on your local net, basic auth may be sufficient. The buttons and all links in the dashboard use Hotwired Turbo which issues HTTP requests using Ajax. Make sure that the basic auth cookie (`Authorization: Basic ...`) is persisted correctly and sent via all browser requests - it should normally work correctly, maybe something is wrong in your deployment. Use the "Network" tab of your Firefox/Chrome developer tools and inspect the Ajax requests and check that the `Authorization` header is present.

If you're running this on the open Internet, the security requirements are much higher. We don't currently support this use case, although it is on our road map long term. There are many mechanisms that can be used here, including:

- Django authentication
- Mutual TLS (e.g. CloudFlare mTLS)
- VPN

Since `pgml_dashboard` is mostly a read-only layer on top of the database which runs `pgml_extension`, we haven't implemented the authentication layer yet. I think that could be a good first step for us to do in the not too distant future.

**Comment by montanalow** [comment]
I'm going to close this until we understand the requirements better.
