### ISSUE TITLE
when I shutdown the docker-compose and restart again the DB is refreshed and all data is lost

### ISSUE THREAD

**Issue by Bilal-Yousaf** [postgresml/postgresml#282]
when I shutdown the docker-compose using docker-compose down and restart again using docker-compose up -d the DB is refreshed and all data is lost.
Is there any way I can keep my db consistent even if I restart.

**Comment by montanalow** [comment]
The data in your docker compose database should persist. I've just confirmed that this works on my local install.  My test was running docker-compose up, creating a view, using ctrl-c to stop the container, re-running docker-compose up, and confirming that the view was still present. How are you storing your data in the db, and how are you starting/stopper docker?

**Comment by Bilal-Yousaf** [comment]
Does pgml stores database outside docker container? Or maps some local directory to store the db?

**Comment by dpereira** [comment]
Usually, if you run `docker-compose down`, the containers will get removed, and I believe the associated volumes, too.

Instead, if you stop the containers by using `ctrl-c` or `docker-compose stop`, the next time you spin them up, the database comes back with whatever was persisted in the volumes from the previous run.

This kind of behavior is common with other compose builds that include other db types, such as mysql, so I'm guessing it could be just the commands being used to stop the containers; `docker-compose down` usually clears the containers and volumes, and it's the expected behavior, as far as I know.

**Comment by montanalow** [comment]
#523

**Comment by zebehringer** [comment]
I typically mount a volume in my docker-compose.yaml file so that `docker compose down` does not remove the data (`docker compose down -v` will remove the data)

Add this under `services:postgres`
```
    volumes:
      - db:/var/lib/postgresql/14
```

and this to the end of the file
```

volumes:
  db:
```
