### ISSUE TITLE
Performance Issues: Where is the memory optimization?

### ISSUE THREAD

**Issue by NLGithubWP** [postgresml/postgresml#823]
I look into the code base and I have two questions. 
1. The project claims using Rust is because it's faster than Python. But it looks like it only happens in the simple algorithm as your team re-build such an algorithm in Rust, and for the transformer, the Rust will still call the Python module and the performance gained by Rust is gone. 
2. As for the memory optimization, when tune the transformer, it goes the following steps
  (1) `let dataset = snapshot.text_dataset();` in `src/orm/model.rs` will call snap.text_dataset function. 
  (2) the text_dataset function will call `let result = client.select(&self.select_sql(), None, None).unwrap();` This will retrieve all records in the database memory !!!!! which will have a huge influence on normal data usage, such as insert or read. Where the memory optimization come from?

**Comment by NLGithubWP** [comment]
3. In the `snapshop.numeric_encoded_dataset()` method, it basically a pre-processing steps. But it seems it will traverse all records and do the preprocessing before training, which is again very slow because the training needs to wait for all data to be pre-processed!!!

**Comment by NLGithubWP** [comment]
I suspect the data preprocessing will takes more time than the model training. Thus, the rust benefit is not so obvious.

**Comment by montanalow** [comment]
[This blog post](https://postgresml.org/blog/postgresml-is-moving-to-rust-for-our-2.0-release ) illustrates how and why PostgresML is faster because it's implemented as a Rust extension to Postgres, rather than pl/Python, with several benchmarks. This holds true for even more complex ML algorithm's like XGBoost and LightGBM. 

The goal to completely remove Python is the 3.0 milestone. That said, we don't exclude functionality for Rust purity when there are only Python implementations available. The industry is moving at break neck speed, releasing new LLMs on an almost daily basis, that are frequently only supported by the original authors in Python. It will take additional time and effort to understand which models are worth porting, but Rust [Torch](https://github.com/postgresml/postgresml/pull/302) support is planned, and huggingface has already released their [tokenizers](https://github.com/huggingface/tokenizers) in Rust, so it appears that more of the industry will be heading in this direction over the longer term.

You seem to be focused on training performance rather than low latency inference. The latter is where PostgresML [receives the largest speedups](https://postgresml.org/blog/postgresml-is-8x-faster-than-python-http-microservices) due to additional architectural concerns like traversing the network. Correctly preprocessing data is often an expensive and overlooked aspect of model training (and then how to repeat that preprocessing correctly during inference), but you do indeed need to pre-process the entire dataset before training to do things like mean encoding etc. Doing this preprocessing with Python Pandas often multiplies the RAM required for training by several factors, and often becomes a dominating latency concern during online inference, due to the (frequently unobvious) transformations between numpy/pandas/arrow/c arrays required when you're working in a memory abastracted language like Python.

If you'd like to help work on more streaming/paging/batch data oriented training implementations (wherever it's feasible), or help port more Python functionality into Rust, those PRs would be welcome. We've still got a long way to go until PostgresML is as good as it can be.

**Comment by montanalow** [comment]
I'm going to close this one in favor of opening specific issues that are more actionable, but feel free to continue the discussion.
